parameters:
#    samenjoy_data.example.class: Samenjoy\DataBundle\Example

services:
#    samenjoy_data.example:
#        class: %samenjoy_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
