imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: Samenjoy
        cookie_lifetime:      600
        save_path:            "%kernel.cache_dir%/sessions"
    fragments:       ~
    http_method_override: true
    serializer:
        enabled: true

# globak parameters
parameters:
    default_locale:            "%locale%"
    adapter_cache_dir:         "%kernel.root_dir%/cache/%kernel.environment%/filesystem"
    adapter_tmp_files:         "%kernel.root_dir%/../SamenjoyTempFiles"
    adapter_files:             "%kernel.root_dir%/../SamenjoyFiles"
    mail_from:                 "do-not-reply@samenjoy.com"
    mail_from_name:            "Samenjoy.com"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SASEdevCommonsBootstrapBundle::form.html.twig'
    globals:
        default_locale: "%locale%"

# Services
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
 
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
 
    twig.extension.i18n:
       class: Twig_Extensions_Extension_I18n
       tags:
           - { name: twig.extension }
 
    twig.extension.array:
       class: Twig_Extensions_Extension_Array
       tags:
           - { name: twig.extension }
 

# serializer.normalizer
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }

#BCC configuration
    bcc.twig.extension:
        class: BCC\ExtraToolsBundle\Twig\TwigExtension
        tags:
            -  { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: "%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php"
            apply_to: \.less$
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# gedmo
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            tree: true
            timestampable: true
            sluggable: true
            translatable: true 

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# sensio framework extra
sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }
    view:    { annotations: true }
    cache:   { annotations: true }

# jms_security_extra
jms_security_extra:
    secure_all_services: true

# knp_paginator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: SASEdevCommonsBootstrapBundle::pagination.html.twig     # sliding pagination controls template
        sortable: SASEdevCommonsBootstrapBundle::sortable_link.html.twig # sort link template


# liip imagine
#liip_imagine:
#    resolvers:
#        default:
#            web_path:
#              web_root: %kernel.root_dir%../web
#              cache_prefix: media/cache


#    loaders:
#        default:
#            filesystem:
#                data_root: %kernel.root_dir%../web/

#    driver:               gd
#    cache:                default
#    data_loader:          default
#    controller_action:    liip_imagine.controller:filterAction

#    filter_sets:
#        cache: ~
#        my_thumb:
#            quality: 75
#            filters:
#                thumbnail: { size: [50, 50], mode: outbound }

# GregwarFormBundle entity_id
gregwar_form: ~

# LuneticsLocaleBundle
lunetics_locale:
    strict_mode: true
    allowed_locales:
        - fr
        - en
        - nl
    guessing_order:
        - query
        - cookie
        - session
        - browser
        - router
    cookie:
        set_on_change: true
    switcher:
        template: SamenjoyFrontBundle:Menu:localeswitch.html.twig

# JMS DI
 
jms_di_extra:
    locations:
        all_bundles: true
        directories: ["%kernel.root_dir%/../src"]
    automatic_controller_injections:
        properties:
            request: "@request"
            router: "@router"
        method_calls:
            setRouter: ["@router"]

pilot_ogone_payment:
    secret:
        shaInKey: ePtvduo6gPmW3MTgnn4PswDM66
        shaOutKey: GTF6cykM6NTnMWjR2mTZqNGd4
        algorithm: sha1
    general:
        PSPID: samenjoyprod
        currency: EUR
        language: fr_FR
        env: prod
    design:
        title: Samenjoy - Payment page
        bgColor: "#4e84c4"
        txtColor: "#FFFFFF"
        tblBgColor: "#FFFFFF"
        buttonBgColor: "#00467F"
        buttonTxtColor: "#FFFFFF"
        fontType: "Verdana"